1. Single Shot Detector (SSD)

2. **COCO** stands for **Common Objects in Context**, as the image dataset was created with the goal of advancing image recognition. The COCO dataset contains challenging, high-quality visual datasets for computer vision, mostly state-of-the-art neural networks.

3. **frozen_inference_graph.pb**, is a frozen graph that cannot be trained anymore

In [54]:
import cv2
import matplotlib.pyplot as plt

In [55]:
config_file='ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
frozen_model='frozen_inference_graph.pb'
label='labels.txt'

In [56]:
model=cv2.dnn_DetectionModel(frozen_model,config_file)

In [57]:
class_labels=[]

with open(label,'rt') as file:
    class_labels=file.read().rstrip('\n').split('\n')

In [ ]:
print(class_labels)

In [ ]:
len(class_labels)

In [ ]:
255/2

In [ ]:
model.setInputSize(320,320) # set size for image frame
model.setInputScale(1.0/127.5)   # set scale value for frame
model.setInputMean((127.5,127,5,127.5))         # set mean value for frame 
model.setInputSwapRB(True)  # It will swap R and B in BGR color channel and make it RGB


In [ ]:
img=cv2.imread('man with.jpeg',1)
plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

In [63]:
class_index,confidence,bbox=model.detect(img,confThreshold=0.5)

In [ ]:
print(class_index)

In [ ]:
print(confidence)

In [ ]:
print(type(confidence))

In [ ]:
print(bbox)

In [68]:
print(type(bbox))

<class 'numpy.ndarray'>


In [78]:
font_scale=0.5
font=cv2.FONT_HERSHEY_SIMPLEX

for classind,conf,box in zip(class_index.flatten(),confidence.flatten(),bbox ):
    cv2.rectangle(img,box,(255,0,0),1)
    cv2.putText(img,class_labels[classind-1],(box[0]+10,box[1]+40),font,font_scale,(0,255,0),1)

In [ ]:
plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))

In [82]:
# videos

cap=cv2.VideoCapture('pexels-george-morina-5932788 (1080p).mp4')
font_scale=0.5
font=cv2.FONT_HERSHEY_SIMPLEX

while True:
    ret,frame=cap.read()
    
    class_index,confidence,bbox=model.detect(frame,confThreshold=0.50)
    
    print(class_index)
    
    if len(class_index)!=0:
        for classind,conf,box in zip(class_index.flatten(),confidence.flatten(),bbox):
            if(classind<=80):
                cv2.rectangle(frame,box,(255,0,0),2)
                cv2.putText(frame,class_labels[classind-1],(box[0]+10,box[1]+40),font,font_scale,(0,255,0),2)
                cv2.putText(frame,str(round(conf*100,1)),(box[0]+100,box[1]+40),font,font_scale,(0,0,255),2)
    
    
    cv2.imshow('Objects detection',frame)
    
    if cv2.waitKey(2) & 0xff==ord('q'):
        break
    
cap.release()
cv2.destroyAllWindows()

[1 6 1 1 1 1]
[1 6 1 1 1 1]
[1 6 1 1 1 1]
[6 1 1 1 1]
[6 1 2 1 1 1]
[6 1 2 1 1 1 1]
[6 1 1 1 1 1 2 1]
[6 1 1 1 2 1]
[6 1 1 1 2]
[6 1 1 1 1 2]
[6 1 1 1 1]
[6 1 1 1 2 1 2]
[6 1 1 1]
[6 1 1 1]
[6 1 1 1]
[6 1 1 1 1]
[6 1 1 1 1]
[6 1 1 1]
[6 1 1 1]
[6 1 1 1]
[6 1 1 1]
[6 1 1 1 1]
[6 1 1 1 1 1]
[6 1 1 1 1 1]
[6 1 1 1]
[6 1 1 1 1 1]
[6 1 1 1 1 6 1]
[6 1 1 1 1]
[6 1 1 6 1 1]
[6 1 1 1 6 1 1 1]
[6 1 1 6 1 1]
[6 6 1 1 1 1 1]
[6 6 1 1 1]
[6 1 1 1 1]
[6 1 1 1]
[6 1 1 1]
[6 6 1 1 1]
[6 6 1 1 1 1]
[6 6 1 1]
[6 1 6 1]
[6 1 1 1 6]
[6 1 1 1 1]
[6 1 1 1]
[6 1 1]
[1 6 1 1 1 1]
[1 6 1 1 1]
[1 6 1 1]
[1 6 1 1]
[1 6 1 1]
[1 6 1 1]
[1 6 1]
[1 1 6]
[1 1 6]
[1 1 6]
[6 1 1 6 1]
[1 1 6 1]
[1 6 1]
[ 1  6  1 31]
[1 6 1]
[ 1  6 31  1]
[1 6 1 1 1 1]
[1 6 1 1]
[1 6 1 1]
[1 1 1 6]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 1]
[ 1  1  1  6 41]
[ 1  1  6 41]
[1 1 6]
[1 1 6]
[1 1 6]
[1 6 1]
[1 6 1]
[1 6 1]
[1 6]
[1 1 6]
[1 1]
[1 1 1]
[1 1 1]
[1 1 1 6 1]
[1 1 1 1 6]
[1 1 1 6]
[1 1 1]
[1 1 1]
[1 1 1]
[1 1 3 1]
[1 